# Customize #########################################################
homeassistant:
  customize:
  # Switches ###########
    switch.mower_mowing:
      friendly_name: Mowing
    switch.mower_home:
      friendly_name: Home
    switch.mower_edgecut:
      friendly_name: Cut-to-edge
    switch.mower_partymode:
      friendly_name: Partymode
    switch.mower_lock:
      friendly_name: Lock

  # Sensors ############
    sensor.landroid_mower_battery:
      friendly_name: Battery charge
      device_class: battery
    sensor.landroid_mower_error:
      friendly_name: Error
    sensor.landroid_mower_status:
      friendly_name: Status

    sensor.mower_ip:
      friendly_name: IP address

    sensor.mower_bladetime:
      friendly_name: Bladetime
    sensor.mower_current_bladetime:
      friendly_name: Current bladetime
    sensor.mower_totaltime:
      friendly_name: Total time
    sensor.mower_distance:
      friendly_name: Distance
    sensor.mower_lastupdate:
      friendly_name: Last update
      icon: mdi:update
    sensor.mower_wifi:
      friendly_name: WiFi quality
    sensor.mower_yaw:
      friendly_name: Yaw
    sensor.mower_roll:
      friendly_name: Roll
    sensor.mower_pitch:
      friendly_name: Pitch

  # Input Selects ######
    input_select.mower_zone:
      friendly_name: Mowing zone

  # Input Numbers ######
    input_number.mower_raindelay:
      friendly_name: Rain delay
    input_number.mower_timeextension:
      friendly_name: Time extension

    input_number.mower_zone0_distance:
      friendly_name: "Mowing zone 0: Distance"
    input_number.mower_zone1_distance:
      friendly_name: "Mowing zone 1: Distance"
    input_number.mower_zone2_distance:
      friendly_name: "Mowing zone 2: Distance"
    input_number.mower_zone3_distance:
      friendly_name: "Mowing zone 3: Distance"

    input_number.mower_zone0_probability:
      friendly_name: "Mowing zone 0: Probability"
    input_number.mower_zone1_probability:
      friendly_name: "Mowing zone 1: Probability"
    input_number.mower_zone2_probability:
      friendly_name: "Mowing zone 2: Probability"
    input_number.mower_zone3_probability:
      friendly_name: "Mowing zone 3: Probability"

  # Input Booleans #####
    input_boolean.mower_sched_settings:
      friendly_name: Settings
    input_boolean.mower_info_toggle:
      friendly_name: Information
    input_boolean.mower_zone_enable:
      friendly_name: Enable multizone

    input_boolean.mower_view_config:
      friendly_name: Configuration
    input_boolean.mower_view_setzones:
      friendly_name: Multizone

    #input_boolean.mower_view_0:
    #  friendly_name: Su.
    #input_boolean.mower_view_1:
    #  friendly_name: Mo.
    #input_boolean.mower_view_2:
    #  friendly_name: Tu.
    #input_boolean.mower_view_3:
    #  friendly_name: We.
    #input_boolean.mower_view_4:
    #  friendly_name: Th.
    #input_boolean.mower_view_5:
    #  friendly_name: Fr.
    #input_boolean.mower_view_6:
    #  friendly_name: Sa.

    #input_boolean.mower_0_sched_enable:
    #  friendly_name: Sunday
    #input_boolean.mower_1_sched_enable:
    #  friendly_name: Monday
    #input_boolean.mower_2_sched_enable:
    #  friendly_name: Tuesday
    #input_boolean.mower_3_sched_enable:
    #  friendly_name: Wednesday
    #input_boolean.mower_4_sched_enable:
    #  friendly_name: Thursday
    #input_boolean.mower_5_sched_enable:
    #  friendly_name: Friday
    #input_boolean.mower_6_sched_enable:
    #  friendly_name: Saturday

    #input_boolean.mower_0_cuttoedge:
    #  friendly_name: Cut-to-edge
    #input_boolean.mower_1_cuttoedge:
    #  friendly_name: Cut-to-edge
    #input_boolean.mower_2_cuttoedge:
    #  friendly_name: Cut-to-edge
    #input_boolean.mower_3_cuttoedge:
    #  friendly_name: Cut-to-edge
    #input_boolean.mower_4_cuttoedge:
    #  friendly_name: Cut-to-edge
    #input_boolean.mower_5_cuttoedge:
    #  friendly_name: Cut-to-edge
    #input_boolean.mower_6_cuttoedge:
    #  friendly_name: Cut-to-edge


  # Automations ########
    automation.mower_notify_status:
      friendly_name: Status notification
      icon: mdi:bell
    automation.mower_notify_error:
      friendly_name: Error notification
      icon: mdi:bell

    automation.mower_sync_values:
      friendly_name: Data synchronization
      icon: mdi:sync

    #automation.mower_views_switch:
    #  friendly_name: Toggle tabs
    #  icon: mdi:tab


# Scripts #########
    script.mower_set_config:
      friendly_name: Apply settings
      icon: mdi:content-save-settings

    script.mower_setzone:
      friendly_name: Zone selection
      icon: mdi:vector-difference

    script.mower_setzones:
      friendly_name: Apply multizone
      icon: mdi:content-save-settings

    script.mower_views_toggle:
      friendly_name: Toggle tabs
      icon: mdi:tab
